### PR TITLE
ci: automatic kokoro label in addition to /gcbrun comment

### PR DESCRIPTION
**Pull request by suztomo**
From reading the configuration (https://github.com/googleapis/repo-automation-bots/pull/1682/files), it accepts multiple objects.

### CODE REVIEW

**Review by kolea2 — APPROVED** [review]

**Comment by kolea2** [comment]
@suztomo, is it possible to make this change here instead? https://github.com/googleapis/synthtool/blob/master/synthtool/gcp/templates/java_library/.github/trusted-contribution.yml

**Comment by suztomo** [comment]
Yes, that's nice idea after we confirm this change works as expected here.

**Comment by suztomo** [comment]
Pull request there is ready https://github.com/googleapis/synthtool/pull/1965.

**Review by JoeWang1127 — APPROVED** [review]

**Comment by suztomo** [comment]
It worked well.

image

**Pull request merged**
