### PR TITLE
chore(test): Add test to verify that query ranges work as expected

### PR DESCRIPTION
**Pull request by igorbernstein2**

### CODE REVIEW

**Comment by bchou1** [comment]
Hi Igor,
Rohan Ramnarine asked me to add some data to help reproduce the issue I'm running into where the CLOSED end range data is not being returned. Here is the integration test that reproduces the issue I'm seeing using the same row key data we have in BigTable and the range key format we use when querying using the client. 

```
  @Test
  public void rangeQueries2() {
    BigtableDataClient client = testEnvRule.env().getDataClient();
    String tableId = testEnvRule.env().getTableId();
    String familyId = testEnvRule.env().getFamilyId();
    String startRange = "login|9223370437392774807";
    String endRange = "login|9223370437392775807";

    String keyA = "login|9223370437392775807|uniqueaa-4bff-44e4-8f55-241f733f8ae";
    String keyZ = "login|9223370437392775807|uniqueda-f31a-4f16-b1ed-c90288d68d62";

    long timestampMicros = System.currentTimeMillis() * 1_000;

    client.bulkMutateRows(
            BulkMutation.create(tableId)
                    .add(RowMutationEntry.create(keyA).setCell(familyId, "", timestampMicros, "A"))
                    .add(RowMutationEntry.create(keyZ).setCell(familyId, "", timestampMicros, "Z")));

    Row expectedRowA =
            Row.create(
                    ByteString.copyFromUtf8(keyA),
                    ImmutableList.of(
                            RowCell.create(
                                    testEnvRule.env().getFamilyId(),
                                    ByteString.copyFromUtf8(""),
                                    timestampMicros,
                                    ImmutableList.<String>of(),
                                    ByteString.copyFromUtf8("A"))));

    Row expectedRowZ =
            Row.create(
                    ByteString.copyFromUtf8(keyZ),
                    ImmutableList.of(
                            RowCell.create(
                                    testEnvRule.env().getFamilyId(),
                                    ByteString.copyFromUtf8(""),
                                    timestampMicros,
                                    ImmutableList.<String>of(),
                                    ByteString.copyFromUtf8("Z"))));

    // Closed/Closed
    assertThat(
            ImmutableList.copyOf(
                    client.readRows(
                            Query.create(tableId)
                                    .range(ByteStringRange.unbounded().startClosed(startRange).endClosed(endRange)))))
            .containsExactly(expectedRowA, expectedRowZ);
  }
```

**Review by kolea2 — APPROVED** [review]

**Comment by igorbernstein2** [comment]
Thanks for putting together the example. However that test failure is expected.
The range [`login|9223370437392774807`, `login|9223370437392775807`] does not include the key `login|9223370437392775807|uniqueda-f31a-4f16-b1ed-c90288d68d62`.

This is because, lexicographically, `prefix` will always come before `prefixSuffix`.

**Comment by bchou1** [comment]
Is there a way to construct the end range in the query such that it matches any row key containing that prefix? The login|<reverse timestamp> is all that we have and the unique id suffix is not known. The only thing I've seen work so far is to change the reverse timestamp itself e.g. use ```9223370437392775808```

**Comment by igorbernstein2** [comment]
ByteStringRange has a method called `prefix` which constructs a range that includes all keys with the supplied prefix. So you can do something like:

```
ByteStringRange startRange = ByteStringRange.prefix(....);
ByteStringRange endRange = ByteStringRange.prefix(....);

Preconditions.checkState(startRange.getStartBound() == BoundType.CLOSED);
Preconditions.checkState(endRange.getEndBound() == BoundType.OPEN);

ByteStringRange combinedRange = ByteStringRange.create(startRange.getStart(), endRange.getEnd());
```

If you have the inclination, I would also appreciate a PR to add a utility method `ByteStringRange ByteStringRange#getBound(ByteStringRange ranges...)`. The implementation would do something similar to RowSetUtil#getBound()

**Pull request merged**
