### PR TITLE
ci: adding sample build

### PR DESCRIPTION
**Pull request by suztomo**
b/322966824

### CODE REVIEW

**Comment by suztomo** [comment]
IAM needs to be set:

```
Caused by: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Access denied. Missing IAM permission: bigtable.tables.list.
	at io.grpc.Status.asRuntimeException(Status.java:537)
```

**Comment by suztomo** [comment]
`Caused by: io.grpc.StatusRuntimeException: NOT_FOUND: Failed to read: projects/{615621127317}/instances/instance`

The braces look strange.

**Comment by suztomo** [comment]
Test-Samples-java-bigtable (cloud-java-ci-sample) Successful in 23m — Summary

**Comment by suztomo** [comment]
Retrying "Kokoro - Test: Integration — Build failed".

**Review by kolea2 — APPROVED** [review]
lgtm for yaml changes

**Review by billyjacobson — APPROVED** [review]

**Comment by suztomo** [comment]
All checks have passed.

Test-Samples-java-bigtable (cloud-java-ci-sample) Successful in 24m — Summary

**Pull request merged**
