### PR TITLE
deps: regenerating with new Protobuf (v2.6.x)

### PR DESCRIPTION
**Pull request by suztomo**
To merge into v2.6.x branch. This PR was generated using Protobuf 3.19.6. Source-Link: https://github.com/googleapis/googleapis/commit/6cce671cb21e5ba9ee785dfe50f5a86b87bb5f21

### CODE REVIEW

**Comment by suztomo** [comment]
OwlBot is failing trying to create a workflow in my branch.

```
Step #8: Error: Command failed: git push --no-verify
Step #8: To https://github.com/suztomo/java-bigtable.git
Step #8:  ! [remote rejected] v2.6.x_patch -> v2.6.x_patch (refusing to allow a GitHub App to create or update workflow `.github/workflows/ci.yaml` without `workflows` permission)
```

**Comment by prash-mi** [comment]
@suztomo The GraalVM  tests are failing, is it expected ?

**Comment by suztomo** [comment]
Yes

**Comment by suztomo** [comment]
OwlBot fails becuase it tries to change workflow in _my_ branch. Templated workflow is not needed for v2.6.x branch.

```
Error: Command failed: git push --no-verify
To https://github.com/suztomo/java-bigtable.git
 ! [remote rejected] v2.6.x_patch -> v2.6.x_patch (refusing to allow a GitHub App to create or update workflow `.github/workflows/ci.yaml` without `workflows` permission)
error: failed to push some refs to 'https://github.com/suztomo/java-bigtable.git'
```

**Review by prash-mi — APPROVED** [review]
Approving as all the required checks are passing

**Pull request merged**
