### PR TITLE
feat: ARM support for gcloud bigtable emulator

### PR DESCRIPTION
**Pull request by rameshdharan**

### CODE REVIEW

**Review by igorbernstein2 — COMMENTED** [review]
lgtm, but lets  wait for the sdk to rollout

**Comment by rameshdharan** [comment]
> lgtm, but lets wait for the sdk to rollout

SDK with the ARM components has now rolled out: 
https://cloud.google.com/sdk/docs/release-notes#36700_2021-12-14

**Comment by igorbernstein2** [comment]
I tried this on my personal m1, and it  failed to download the binaries. I havent had a chance to debug, but we should wait to merge

**Review by igorbernstein2 — APPROVED** [review]
lgtm

**Comment by sap1ens** [comment]
Hey folks, thanks for doing this! When should we expect a new release of the library including this change?

**Pull request merged**
