### PR TITLE
feat: include User agent

### PR DESCRIPTION
**Pull request by igorbernstein2**
Configure the UserAgent in addition to x-goog-api-client. This will be needed for DirectPath

This depends on #398 for the test changes

### CODE REVIEW

**Comment by igorbernstein2** [comment]
ok, lets leave this be and I'll address it in the next release

**Comment by igorbernstein2** [comment]
I updated gax to workaround this issue. We just need a new release of gax (> 1.58.3) and then we should able to merge this

**Comment by WeiranFang** [comment]
@igorbernstein2 Seems gax-java has just released 1.59.0, which has your changes:)

**Comment by igorbernstein2** [comment]
Waiting on https://github.com/googleapis/java-shared-dependencies/pull/160 to be pushed to maven

**Comment by igorbernstein2** [comment]
Will merge this after https://github.com/googleapis/java-bigtable/pull/442

**Comment by igorbernstein2** [comment]
Confirmed that after #442, this no longer breaks java-bigtable-hbase

**Review by kolea2 — APPROVED** [review]

**Pull request merged**
