### PR TITLE
chore(deps): manually updating the Libraries BOM

### PR DESCRIPTION
**Pull request by suztomo**
Somehow the RenovateBot stopped working for libraries-bom
in this repository. Troubleshooting:
https://github.com/googleapis/synthtool/issues/1844

Followed https://github.com/googleapis/java-bigtable/pull/1868/files to locate the files.

### CODE REVIEW

**Comment by suztomo** [comment]
samples/snippets/pom.xml is templated, really?

**Comment by suztomo** [comment]
No, samples/snippets/pom.xml is not templated.

**Review by JoeWang1127 — APPROVED** [review]
Approve with a question: do we need to manually update the version in each release cycle?

**Comment by suztomo** [comment]
No, that's not in the todo items.

I'm experimenting how RenovateBot reacts after I manually update these lines.

**Pull request merged**
